language: java

jdk:
  - oraclejdk7

before_install:
  - chmod +x ./.travis/maven-build.sh
  - chmod +x ./.travis/call-creation.sh
  - mvn clean

script: "./.travis/maven-build.sh"

after_deploy: "./.travis/call-creation.sh"

notifications:
  email: false
  slack:
    secure: ciAOsdv9lf/IbAwyzeR/z2nlBSevmBHBqca6tf0Yh2DIyAx/uUo1ojon0W7Kv6tCECGhSTdfQAnZ+nFjjqaRs+Jq4svd9WKYrFuZyOWmT31iSJ/nvPymRvevSsgwpSKr0nJS9dxePKto/T3ozW29kx88eaJQH17zOaX2rfuIje4=
  webhooks:
    on_success: always
    on_failure: always
    on_start: never

env:
  global:
    - secure: UG+b1tEgc8xv9x4r//2OAIK1RrYv6n209KTTFMMwcnAa7DI8HaP8nljRa5/VhDhuKHdlVrYH/tI90v7UVBs0GDVNwK5V17Io0fMm3FUGZekSthTCqqno5wAGa9r6a6mMLtSaSmIFeIKi0+0d2ZwplRuhj/dtEYjjBBj+kK8g4nE=
    - secure: St/fecUDInFBCRriYqgp2F8PU9/SooorgxD9Mrs+b0EsC7AbtSsQXvdIv2Lp6xzdQ0VSXPcLIhULPOYrmBKnGQ/NjXTIZXxnroyQxxnI6xyEWIZwiHRY/bKRJDRbQTxD9NL32szKiDSwnw7pu6llF4D64UqQvziq4Gm6VohU75M=
    - secure: bD15GVZWowiknbfLavh8CxSh0GsnF5kT4kZ6ggCuUDGyj0mzqf7dNRnchQIKkCG0WRYyTrFN4pEiygeywWsipEeAVv9Xhx3cuUZmzeQaR5KCWabSwJ8gK6jZd1YhcWmM9vrdPHobZr65MP0y/8mu/Fovgky9dY7KDf4G3SebNrM=
    - RANDOMS_VERSION=0.1

cache:
  directories:
    - ".autoconf"
    - "$HOME/.m2"

deploy:
  - provider: s3
    access_key_id: AKIAJDZLZNH2PIKHUKOA
    secret_access_key:
      secure: Cvh05YiopxAxjERHnnsSQwVa6570+ob8igtbWMoctv0u8AMGgcSlRWXJksSiK1nQjmjpmDUOwuu0JIGwIk2hA4Nzn20WLkJm2vyrei/kgrdcfsMzA9M4B9uJsUNx1ETQGtr9IpE/YGyzwTT5s1SovtvHZvF2LLjeWZXAQkaIM7qSS69s+cSRhSTLxkocmOVl4GguNqlZbYaH8wDhHl0oWv/j6+aJCjiH/4YyzeoB0GC5u9TWCifmdza95UAFeoS8CfuEYGEMcoxQq4SNZ4TchHiEUkSuugDi2xYrFDKvhL+2eCkrW3h7OXuihFjrm7V1DxFzZ53W0LzS57s5ttXu2b6Glgei55ey7y0kI7j6K2dn/bz7v8YHP+mEW+JGSGZZsWtfa1VXZA49qAx9gUlRG3rI8PhIWNtrFIYl4+xc4E6PncoMGUzD4g4aj/to/+z8NSMAFgerGjTqkZIs9nicxl/Oi6GFSbBEZqyTIJ3dhtPgQILaehswAnkhwYA6M2JFD7tGUOxq6jz6/nWvpeooY61iVBc6NLNnB6CDYK7ka3bNOU4AXuL/Q4FTSfpJNWmpOlVc3xon7xoByQvhKA4QThTCrX959vJaO5wuWMrUosiVC/nq3j/+kvWoJLZ+cpQAV2k0h7hvHqCBQSsSe47z9gJJ5Y9fbo5v35MZT8ZlUzU=
    bucket: parabot
    skip_cleanup: true
    local-dir: "./target/final/"
    upload-dir: "artifacts/randoms"
    region: us-west-1
    detect_encoding: true
    acl: public_read
    on:
      repo: Parabot/Randoms
      all_branches: true